# Generated by Django 3.0.5 on 2020-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0002_auto_20200606_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default=' ', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(default=' ', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=' ', max_length=10000000),
        ),
    ]
