# Generated by Django 3.0.5 on 2020-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0003_auto_20200606_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
