# Generated by Django 3.0.5 on 2020-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0004_auto_20200606_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default=' ', max_length=10000000),
        ),
    ]
