# Generated by Django 3.0.5 on 2020-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0005_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Genres',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
