# Generated by Django 3.0.5 on 2020-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0006_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
