# Generated by Django 3.0.5 on 2020-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0007_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genres',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.CharField(default=' ', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(default=' ', max_length=100000000),
        ),
    ]
