# Generated by Django 3.0.5 on 2020-06-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0010_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='boxoffice',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
