# Generated by Django 3.0.5 on 2020-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0012_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='No_of_Movies',
            new_name='no_of_movies',
        ),
        migrations.RemoveField(
            model_name='year',
            name='Movie',
        ),
        migrations.AddField(
            model_name='year',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='YearMovies', to='movi.Movie'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default=' ', max_length=20)),
                ('no_of_movies', models.IntegerField(default=0)),
                ('movie', models.ManyToManyField(blank=True, related_name='RatingMovies', to='movi.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(default=' ', max_length=20)),
                ('no_of_movies', models.IntegerField(default=0)),
                ('movie', models.ManyToManyField(blank=True, related_name='GenresMovies', to='movi.Movie')),
            ],
        ),
    ]
