# Generated by Django 3.0.5 on 2020-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0013_auto_20200609_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=' ', max_length=500)),
                ('lastName', models.CharField(default=' ', max_length=500)),
                ('email', models.CharField(default=' ', max_length=1000)),
                ('subject', models.CharField(default=' ', max_length=1000)),
                ('message', models.CharField(default=' ', max_length=1000000)),
            ],
        ),
    ]
