# Generated by Django 3.0.5 on 2020-06-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0014_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='firstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='lastName',
            new_name='Last_Name',
        ),
    ]
