# Generated by Django 3.0.5 on 2020-06-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0016_auto_20200618_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default=' ', max_length=10000),
        ),
    ]
