# Generated by Django 3.0.5 on 2020-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0017_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie_name', models.CharField(default=' ', max_length=10000)),
                ('link', models.CharField(default=' ', max_length=1000000000)),
            ],
        ),
    ]
