# Generated by Django 3.0.5 on 2020-06-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0018_serie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Series',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Serie_name',
            new_name='Series_name',
        ),
    ]
