# Generated by Django 3.0.5 on 2020-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0020_auto_20200620_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=' ', max_length=20)),
                ('no_of_movies', models.IntegerField(default=0)),
                ('movie', models.ManyToManyField(blank=True, related_name='LanguageMovies', to='movi.Movie')),
            ],
        ),
    ]
